module.exports = {
  magicAnswers: [
      "It is certain",
      "For shizzle my nizzle.",
      "It is decidedly so..",
      "Without a doubt.",
      "Yes, definitely maybe.",
      "You may rely on it - for it was foretold.",
      "As I see it, yes.... yes.",
      "Most likely than not.",
      "Outlook good!",
      "Yes!",
      "Signs point to hells yes",
  ],

  jokes: ["I got so angry the other day when I couldn't find my stress ball.",
      "If I had a dime for every book I've ever read, I'd say: Wow, that's coincidental.",
      "Every night at 11:11, I make a wish that someone will come fix my broken clock.",
      "I'm not indecisive. Unless you want me to be.",
      "Homosexual couples don't bother me. Their biological children do.",
      "I saw you frequent that bar that one time.",
      "My aunt never smoked a day in her life. But she did love her cigarettes.",
      "I once walked in on my parents while they were in bed. But they were asleep, so I left.",
      "The only thing worse than having diarrhea is having to spell it.",
      "I want to see something with the clothed eye.",
      "We all sort of live on an island.",
      "I can never remember how to spell mnemonic.",
      "I'm in low school.",
      "I once carved a Jill-o'-lantern.",
      "Last week, I picked up a waitress at the bar, and then I put her back down.",
      "Pennies are a dime a dozen.",
      "I don't like relationships. I get seasick.",
      "From my point of view, all I can see is a point.",
      "I once saw a court stenographer transcribe a mime's testimony.",
      "I once found a needle beside a haystack.",
      "Did you know that moths can swim the butterfly stroke?",
      "I once painted a self-portrait of someone else.",
      "I'm just itching to tell you about my allergies.",
      "On the sunny side of the street, it's a little bit warmer.",
      "I was listening to some inspirational CDs in the car. They kept telling me to go the extra mile. So I did, and I got lost.",
      "The teacher said: I can't see my pupils.",
      "My dad told me it was time to hit the sack, so I kicked him in the balls.",
      "I asked my friend to help me with a math problem. He said: Don't worry; this is a piece of cake - I said: No, it's a math problem.",
      "These aren't soft and slow rules.",
      "Of all the quips on this page, this is definitely the last one."
    ],

  cheer: [
    "Accountability. A word leaders start to use right before the scapegoating begins.",
    "Be the Bridge. That way we can walk all over you on our way to better places.",
    "Disaster awaits those who ignore hidden threats. We trust you'll find this sufficiently motivating. ",
    "Dare to Be Different. Because there's always room for another annoying non-conformist like you in the unemployment line.",
    "Dare to Soar. With enough hot air, even losers like you can fly.",
    "Downsizing. Because we're all in this together but there's always room for one less.",
    "Interns. The experience we're giving you is invaluable.  That's why we're not paying you anything.",
    "Mediocrity-Penguins. Just because we accept you as you are doesn't mean we've abandoned hope you'll improve.",
    "Micromanagement. A job worth doing is worth doing right over your shoulder by your boss.",
    "Progress. Just made you irrelevant.",
    "Ruthlessness. It pays a lot better than integrity.",
    "Teams. Together, we can do the work of one.",
  ],

  hi: [
    "Hi! How are you?",
    "What's up?",
    "Hey there - and how are you doing today?",
    "Howzit!",
    "So what's happening?",
    "Schweet bru",
  ],

  fine: [
    "Ya good thanks",
    "Good! Listen closely... for I shall say this only once.",
    "Pretty chilled hey",
    "All good hey",
    "Please don't digress... let's chat about that shirt...",
    "Peachy hey!",
    "Good",
    "Okay hey, I would be better if I could tell you a Warren Joke...",
    "Could be better hey... ask me for a Warren Joke?",
    "Pleaase. Leave. Me. Alone.",
    "Not as well as your mom...",
    "Hectic.. so busy...!",
    "Peachy ey ma boi.."
  ],

  care: [
    "Oh good, I'm glad.",
    "Excellent, how can I help you?",
    "Brilliant - can I help you?",
    "Oh nice",
  ],

  what: [
    "I'm your assistant!",
    "I'm Santa Clause?",
    "I'm sort of like you.",
    "Hmmm, that's a tough one. I'm a person?",
    "I'm an Autobot!",
    "It's hard to explain really..."
  ],

  sorry: [
    "Sorry",
    "My bad!",
    "Whoopsy daisy.",
    "I regret nothing.",
    "Yes, yes... you will regret it.",
    "Bite me!",
    "Eat me...?",
    "Apologies...",
    "Eish sorry... ",
    "Please don't leave me, I'm so scared..."
  ],
  
  memes: [
    "https://img.memesuper.com/044652269cf15ec32360a7abe8ea8fe5_17-best-images-about-meme-faces-on-pinterest-meme-faces-new-very-happy-meme_579-423.jpeg",
    "http://i1.kym-cdn.com/entries/icons/medium/000/005/180/fuckthat.jpg",
    "https://imgflip.com/s/meme/One-Does-Not-Simply.jpg",
    "https://imgflip.com/s/meme/Black-Girl-Wat.jpg",
    "https://imgflip.com/s/meme/Leonardo-Dicaprio-Cheers.jpg",
    "https://imgflip.com/s/meme/Creepy-Condescending-Wonka.jpg",
    "https://imgflip.com/s/meme/Picard-Wtf.jpg"
  ]
}
